name: Daily GitHub Data Collection

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch: # NOTE: デバッグのために追加

env:
  AWS_REGION: 'ap-northeast-1'
  DATE: $(date -d "yesterday" +%Y-%m-%d)

permissions:
  id-token: write
  contents: read

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials with IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_LAMBDA_ROLE_ARN}}

      - name: Invoke Lambda function
        run: |
          aws lambda invoke \
            --function-name AddingCommitsLambda \
            --payload '{"dateString": "'$DATE'"}' \
            response.json
          cat response.json
