name: Daily GitHub Data Collection

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Call Lambda with previous day's date
        run: |
          DATE=$(date -d "yesterday" '+%Y-%m-%d')
          aws lambda invoke \
            --function-name GitHubCommitLambda \
            --payload "{\"repo_name\": \"owner/repo\", \"target_date\": \"$DATE\"}" \
            response.json
