name: Deploy Adding Commits Lambda on Push

on:
  push:
    paths:
      - 'lambda/**'
      - '.github/workflows/deploy-lambda.yml'

env:
  AWS_REGION: 'ap-northeast-1'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lambda

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials with IAM Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_LAMBDA_ROLE_ARN}}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install Dependencies
        run: |
          npm install
          npm run build

      - name: Move node_modules to dist
        run: mv node_modules dist/node_modules

      - name: Zip Lambda function
        run: |
          zip -r ../lambda.zip .

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code --function-name AddingCommitsLambda --zip-file fileb://lambda.zip --publish
